### PR TITLE
Explain game concept in README

### PR DESCRIPTION
**Pull request by dbrgn**
Is this correct, @rnestler @schmijos? (And btw, does Luz have a Github account?)

### CODE REVIEW

**Comment by schmijos** [comment]
Not exactly. It's not limited to 3 players. But the concept is that strengths are weighted and aligned in a circle. You can also play with five players:

**Comment by dbrgn** [comment]
Ah, true :)

**Comment by dbrgn** [comment]
Fixed.

**Comment by schmijos** [comment]
The game logic should also allow 2 players to play against each other but with equal strength.

**Comment by dbrgn** [comment]
Wouldn't that be quite boring?

**Comment by schmijos** [comment]
If that is the case I think we should adjust the game logic to be pleasing for 2 players at least. I think games are more often played if they can be played by two people. Also if you take NPCs or tournaments into account:

**1-on-1 should be interesting in any game.**

**Comment by dbrgn** [comment]
Bang! could be played by 2 people. But it's not fun. That's no reason to claim that any card game should be playable by 2 people :)

The question is: What factor would cause one or the other player to win? Speed? Micromanagement?

**Comment by schmijos** [comment]
I've another idea for the game concept:

An alternative would be to apply the _rock-paper-scissors_ approach onto location-rotation of the pawns in the game. Strength would be weighted based on a vector field which may manifest in the following strength proportions. Arrow means that one entity has an advantage over another:

triangles

**Comment by dbrgn** [comment]
Wouldn't that result in two players just going in circles trying to get behind the other player?

The concept you're proposing is this, right?

```
if p2.y > window.height / 2:
    if p1.x > p2.x:
        # p1 has advantage over p2
    else:
        # p2 has advantage over p1
else:
    if p1.x < p2.x:
        # p1 has advantage over p2
    else:
        # p2 has advantage over p1
```

**Comment by dbrgn** [comment]
Ah wait, I forgot that you can fire weapons without having direct contact... But the concept is very hard to explain in a single sentence, isn't it?

**Comment by schmijos** [comment]
The advantage of using a vector field would be that it's easily adjustable for different game modes. Also it makes calculation of strength distribution weights easy.

And remember: you're not supposed to only time your attacks correctly but also to place your defences right (maybe defence values can be calculated by a different vector field?).

Imagine the possibilities by having a look at the following pictures. The first one shows the mode we described above. The second image shows the calculated advantage over a player in his visus.





How would a vector field for _1-on-1_ capture the flag look like? I imagine it to be corridor from base _A_ to base _B_ where in every point strength of _A_ is equal to defence of _B_. If you're player _A_ this makes it easy to retrieve the flag from _B_ being near base _B_

**Comment by rnestler** [comment]
As the benevolent dictator of this project I decide to keep the game-play simple (the rock-paper-scissor approach) at first to keep the implementation easy.

But we definitely should add this idea with the vector field to [ideas.md](https://github.com/coredump-ch/rpsrtsrs/blob/master/ideas.md)!

**Comment by schmijos** [comment]
You're right. Keep it simple. I'll take this concept over to [ideas.md](https://github.com/coredump-ch/rpsrtsrs/blob/master/ideas.md)!. But still: keep in mind that _rock-paper-scissors_ can be played by two.

**Pull request merged**
