### PR TITLE
Docs

### PR DESCRIPTION
**Pull request by dbrgn**
I pulled a @steveklabnik and added more docs :)

Furthermore, I added travis-cargo, so if everything works out docs should now be built automatically.

### CODE REVIEW

**Comment by dbrgn** [comment]
libsdl2-dev does not seem to work via whitelisting yet :(

**Comment by dbrgn** [comment]
Once again, coveralls fails. Let's get rid of it.

**Comment by steveklabnik** [comment]
Nice :+1:

**Comment by dbrgn** [comment]
Removed coveralls.

Docs uploading only works on master, so we'll have to merge to test.

**Pull request merged**
