### PR TITLE
changed 50 to STDSIZE

### PR DESCRIPTION
**Pull request by Luz**

### CODE REVIEW

**Comment by rnestler** [comment]
@Luz Do you want to edit the commit so that the email address is correct?

**Comment by rnestler** [comment]
See https://de.atlassian.com/git/tutorials/rewriting-history/git-commit--amend: With `git commit --amend --reset-author` you can change the author of the last commit.

**Comment by dbrgn** [comment]
Is this outdated by now?

**Comment by rnestler** [comment]
Yes its trivial and would need rebasing. Closing.

**Pull request closed without merging**
